// flow-typed signature: 2be7b9c8cc42d0be166c7f6dc689e232
// flow-typed version: <<STUB>>/rxjs-es_v^5.0.0-beta.12/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rxjs-es'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'rxjs-es' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rxjs-es/add/observable/bindCallback' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/observable/bindNodeCallback' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/observable/combineLatest' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/observable/concat' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/observable/defer' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/observable/dom/ajax' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/observable/dom/webSocket' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/observable/empty' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/observable/forkJoin' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/observable/from' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/observable/fromEvent' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/observable/fromEventPattern' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/observable/fromPromise' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/observable/generate' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/observable/if' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/observable/interval' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/observable/merge' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/observable/never' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/observable/of' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/observable/onErrorResumeNext' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/observable/pairs' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/observable/race' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/observable/range' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/observable/throw' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/observable/timer' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/observable/using' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/observable/zip' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/audit' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/auditTime' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/buffer' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/bufferCount' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/bufferTime' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/bufferToggle' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/bufferWhen' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/cache' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/catch' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/combineAll' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/combineLatest' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/concat' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/concatAll' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/concatMap' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/concatMapTo' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/count' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/debounce' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/debounceTime' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/defaultIfEmpty' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/delay' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/delayWhen' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/dematerialize' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/distinct' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/distinctKey' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/distinctUntilChanged' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/distinctUntilKeyChanged' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/do' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/elementAt' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/every' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/exhaust' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/exhaustMap' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/expand' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/filter' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/finally' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/find' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/findIndex' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/first' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/groupBy' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/ignoreElements' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/isEmpty' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/last' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/let' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/map' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/mapTo' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/materialize' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/max' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/merge' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/mergeAll' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/mergeMap' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/mergeMapTo' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/mergeScan' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/min' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/multicast' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/observeOn' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/onErrorResumeNext' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/pairwise' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/partition' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/pluck' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/publish' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/publishBehavior' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/publishLast' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/publishReplay' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/race' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/reduce' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/repeat' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/repeatWhen' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/retry' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/retryWhen' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/sample' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/sampleTime' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/scan' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/sequenceEqual' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/share' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/single' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/skip' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/skipUntil' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/skipWhile' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/startWith' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/subscribeOn' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/switch' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/switchMap' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/switchMapTo' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/take' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/takeLast' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/takeUntil' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/takeWhile' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/throttle' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/throttleTime' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/timeInterval' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/timeout' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/timeoutWith' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/timestamp' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/toArray' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/toPromise' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/window' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/windowCount' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/windowTime' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/windowToggle' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/windowWhen' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/withLatestFrom' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/zip' {
  declare module.exports: any;
}

declare module 'rxjs-es/add/operator/zipAll' {
  declare module.exports: any;
}

declare module 'rxjs-es/AsyncSubject' {
  declare module.exports: any;
}

declare module 'rxjs-es/BehaviorSubject' {
  declare module.exports: any;
}

declare module 'rxjs-es/InnerSubscriber' {
  declare module.exports: any;
}

declare module 'rxjs-es/Notification' {
  declare module.exports: any;
}

declare module 'rxjs-es/Observable' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/ArrayLikeObservable' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/ArrayObservable' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/bindCallback' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/bindNodeCallback' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/BoundCallbackObservable' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/BoundNodeCallbackObservable' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/combineLatest' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/concat' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/ConnectableObservable' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/defer' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/DeferObservable' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/dom/ajax' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/dom/AjaxObservable' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/dom/webSocket' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/dom/WebSocketSubject' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/empty' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/EmptyObservable' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/ErrorObservable' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/forkJoin' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/ForkJoinObservable' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/from' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/fromEvent' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/FromEventObservable' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/fromEventPattern' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/FromEventPatternObservable' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/FromObservable' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/fromPromise' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/GenerateObservable' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/if' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/IfObservable' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/interval' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/IntervalObservable' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/IteratorObservable' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/merge' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/MulticastObservable' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/never' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/NeverObservable' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/of' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/pairs' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/PairsObservable' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/PromiseObservable' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/range' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/RangeObservable' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/ScalarObservable' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/SubscribeOnObservable' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/throw' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/timer' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/TimerObservable' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/using' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/UsingObservable' {
  declare module.exports: any;
}

declare module 'rxjs-es/observable/zip' {
  declare module.exports: any;
}

declare module 'rxjs-es/Observer' {
  declare module.exports: any;
}

declare module 'rxjs-es/Operator' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/audit' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/auditTime' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/buffer' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/bufferCount' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/bufferTime' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/bufferToggle' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/bufferWhen' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/cache' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/catch' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/combineAll' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/combineLatest' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/concat' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/concatAll' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/concatMap' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/concatMapTo' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/count' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/debounce' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/debounceTime' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/defaultIfEmpty' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/delay' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/delayWhen' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/dematerialize' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/distinct' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/distinctKey' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/distinctUntilChanged' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/distinctUntilKeyChanged' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/do' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/elementAt' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/every' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/exhaust' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/exhaustMap' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/expand' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/filter' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/finally' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/find' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/findIndex' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/first' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/groupBy' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/ignoreElements' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/isEmpty' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/last' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/let' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/map' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/mapTo' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/materialize' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/max' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/merge' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/mergeAll' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/mergeMap' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/mergeMapTo' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/mergeScan' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/min' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/multicast' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/observeOn' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/onErrorResumeNext' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/pairwise' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/partition' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/pluck' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/publish' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/publishBehavior' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/publishLast' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/publishReplay' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/race' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/reduce' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/repeat' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/repeatWhen' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/retry' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/retryWhen' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/sample' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/sampleTime' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/scan' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/sequenceEqual' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/share' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/single' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/skip' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/skipUntil' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/skipWhile' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/startWith' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/subscribeOn' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/switch' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/switchMap' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/switchMapTo' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/take' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/takeLast' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/takeUntil' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/takeWhile' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/throttle' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/throttleTime' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/timeInterval' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/timeout' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/timeoutWith' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/timestamp' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/toArray' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/toPromise' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/window' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/windowCount' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/windowTime' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/windowToggle' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/windowWhen' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/withLatestFrom' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/zip' {
  declare module.exports: any;
}

declare module 'rxjs-es/operator/zipAll' {
  declare module.exports: any;
}

declare module 'rxjs-es/OuterSubscriber' {
  declare module.exports: any;
}

declare module 'rxjs-es/ReplaySubject' {
  declare module.exports: any;
}

declare module 'rxjs-es/Rx' {
  declare module.exports: any;
}

declare module 'rxjs-es/Scheduler' {
  declare module.exports: any;
}

declare module 'rxjs-es/scheduler/Action' {
  declare module.exports: any;
}

declare module 'rxjs-es/scheduler/animationFrame' {
  declare module.exports: any;
}

declare module 'rxjs-es/scheduler/AnimationFrameAction' {
  declare module.exports: any;
}

declare module 'rxjs-es/scheduler/AnimationFrameScheduler' {
  declare module.exports: any;
}

declare module 'rxjs-es/scheduler/asap' {
  declare module.exports: any;
}

declare module 'rxjs-es/scheduler/AsapAction' {
  declare module.exports: any;
}

declare module 'rxjs-es/scheduler/AsapScheduler' {
  declare module.exports: any;
}

declare module 'rxjs-es/scheduler/async' {
  declare module.exports: any;
}

declare module 'rxjs-es/scheduler/AsyncAction' {
  declare module.exports: any;
}

declare module 'rxjs-es/scheduler/AsyncScheduler' {
  declare module.exports: any;
}

declare module 'rxjs-es/scheduler/queue' {
  declare module.exports: any;
}

declare module 'rxjs-es/scheduler/QueueAction' {
  declare module.exports: any;
}

declare module 'rxjs-es/scheduler/QueueScheduler' {
  declare module.exports: any;
}

declare module 'rxjs-es/scheduler/VirtualTimeScheduler' {
  declare module.exports: any;
}

declare module 'rxjs-es/src/Rx.global' {
  declare module.exports: any;
}

declare module 'rxjs-es/Subject' {
  declare module.exports: any;
}

declare module 'rxjs-es/SubjectSubscription' {
  declare module.exports: any;
}

declare module 'rxjs-es/Subscriber' {
  declare module.exports: any;
}

declare module 'rxjs-es/Subscription' {
  declare module.exports: any;
}

declare module 'rxjs-es/symbol/iterator' {
  declare module.exports: any;
}

declare module 'rxjs-es/symbol/observable' {
  declare module.exports: any;
}

declare module 'rxjs-es/symbol/rxSubscriber' {
  declare module.exports: any;
}

declare module 'rxjs-es/testing/ColdObservable' {
  declare module.exports: any;
}

declare module 'rxjs-es/testing/HotObservable' {
  declare module.exports: any;
}

declare module 'rxjs-es/testing/SubscriptionLog' {
  declare module.exports: any;
}

declare module 'rxjs-es/testing/SubscriptionLoggable' {
  declare module.exports: any;
}

declare module 'rxjs-es/testing/TestMessage' {
  declare module.exports: any;
}

declare module 'rxjs-es/testing/TestScheduler' {
  declare module.exports: any;
}

declare module 'rxjs-es/util/AnimationFrame' {
  declare module.exports: any;
}

declare module 'rxjs-es/util/applyMixins' {
  declare module.exports: any;
}

declare module 'rxjs-es/util/ArgumentOutOfRangeError' {
  declare module.exports: any;
}

declare module 'rxjs-es/util/assign' {
  declare module.exports: any;
}

declare module 'rxjs-es/util/EmptyError' {
  declare module.exports: any;
}

declare module 'rxjs-es/util/errorObject' {
  declare module.exports: any;
}

declare module 'rxjs-es/util/FastMap' {
  declare module.exports: any;
}

declare module 'rxjs-es/util/Immediate' {
  declare module.exports: any;
}

declare module 'rxjs-es/util/isArray' {
  declare module.exports: any;
}

declare module 'rxjs-es/util/isDate' {
  declare module.exports: any;
}

declare module 'rxjs-es/util/isFunction' {
  declare module.exports: any;
}

declare module 'rxjs-es/util/isNumeric' {
  declare module.exports: any;
}

declare module 'rxjs-es/util/isObject' {
  declare module.exports: any;
}

declare module 'rxjs-es/util/isPromise' {
  declare module.exports: any;
}

declare module 'rxjs-es/util/isScheduler' {
  declare module.exports: any;
}

declare module 'rxjs-es/util/Map' {
  declare module.exports: any;
}

declare module 'rxjs-es/util/MapPolyfill' {
  declare module.exports: any;
}

declare module 'rxjs-es/util/noop' {
  declare module.exports: any;
}

declare module 'rxjs-es/util/not' {
  declare module.exports: any;
}

declare module 'rxjs-es/util/ObjectUnsubscribedError' {
  declare module.exports: any;
}

declare module 'rxjs-es/util/root' {
  declare module.exports: any;
}

declare module 'rxjs-es/util/subscribeToResult' {
  declare module.exports: any;
}

declare module 'rxjs-es/util/toSubscriber' {
  declare module.exports: any;
}

declare module 'rxjs-es/util/tryCatch' {
  declare module.exports: any;
}

declare module 'rxjs-es/util/UnsubscriptionError' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rxjs-es/add/observable/bindCallback.js' {
  declare module.exports: $Exports<'rxjs-es/add/observable/bindCallback'>;
}
declare module 'rxjs-es/add/observable/bindNodeCallback.js' {
  declare module.exports: $Exports<'rxjs-es/add/observable/bindNodeCallback'>;
}
declare module 'rxjs-es/add/observable/combineLatest.js' {
  declare module.exports: $Exports<'rxjs-es/add/observable/combineLatest'>;
}
declare module 'rxjs-es/add/observable/concat.js' {
  declare module.exports: $Exports<'rxjs-es/add/observable/concat'>;
}
declare module 'rxjs-es/add/observable/defer.js' {
  declare module.exports: $Exports<'rxjs-es/add/observable/defer'>;
}
declare module 'rxjs-es/add/observable/dom/ajax.js' {
  declare module.exports: $Exports<'rxjs-es/add/observable/dom/ajax'>;
}
declare module 'rxjs-es/add/observable/dom/webSocket.js' {
  declare module.exports: $Exports<'rxjs-es/add/observable/dom/webSocket'>;
}
declare module 'rxjs-es/add/observable/empty.js' {
  declare module.exports: $Exports<'rxjs-es/add/observable/empty'>;
}
declare module 'rxjs-es/add/observable/forkJoin.js' {
  declare module.exports: $Exports<'rxjs-es/add/observable/forkJoin'>;
}
declare module 'rxjs-es/add/observable/from.js' {
  declare module.exports: $Exports<'rxjs-es/add/observable/from'>;
}
declare module 'rxjs-es/add/observable/fromEvent.js' {
  declare module.exports: $Exports<'rxjs-es/add/observable/fromEvent'>;
}
declare module 'rxjs-es/add/observable/fromEventPattern.js' {
  declare module.exports: $Exports<'rxjs-es/add/observable/fromEventPattern'>;
}
declare module 'rxjs-es/add/observable/fromPromise.js' {
  declare module.exports: $Exports<'rxjs-es/add/observable/fromPromise'>;
}
declare module 'rxjs-es/add/observable/generate.js' {
  declare module.exports: $Exports<'rxjs-es/add/observable/generate'>;
}
declare module 'rxjs-es/add/observable/if.js' {
  declare module.exports: $Exports<'rxjs-es/add/observable/if'>;
}
declare module 'rxjs-es/add/observable/interval.js' {
  declare module.exports: $Exports<'rxjs-es/add/observable/interval'>;
}
declare module 'rxjs-es/add/observable/merge.js' {
  declare module.exports: $Exports<'rxjs-es/add/observable/merge'>;
}
declare module 'rxjs-es/add/observable/never.js' {
  declare module.exports: $Exports<'rxjs-es/add/observable/never'>;
}
declare module 'rxjs-es/add/observable/of.js' {
  declare module.exports: $Exports<'rxjs-es/add/observable/of'>;
}
declare module 'rxjs-es/add/observable/onErrorResumeNext.js' {
  declare module.exports: $Exports<'rxjs-es/add/observable/onErrorResumeNext'>;
}
declare module 'rxjs-es/add/observable/pairs.js' {
  declare module.exports: $Exports<'rxjs-es/add/observable/pairs'>;
}
declare module 'rxjs-es/add/observable/race.js' {
  declare module.exports: $Exports<'rxjs-es/add/observable/race'>;
}
declare module 'rxjs-es/add/observable/range.js' {
  declare module.exports: $Exports<'rxjs-es/add/observable/range'>;
}
declare module 'rxjs-es/add/observable/throw.js' {
  declare module.exports: $Exports<'rxjs-es/add/observable/throw'>;
}
declare module 'rxjs-es/add/observable/timer.js' {
  declare module.exports: $Exports<'rxjs-es/add/observable/timer'>;
}
declare module 'rxjs-es/add/observable/using.js' {
  declare module.exports: $Exports<'rxjs-es/add/observable/using'>;
}
declare module 'rxjs-es/add/observable/zip.js' {
  declare module.exports: $Exports<'rxjs-es/add/observable/zip'>;
}
declare module 'rxjs-es/add/operator/audit.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/audit'>;
}
declare module 'rxjs-es/add/operator/auditTime.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/auditTime'>;
}
declare module 'rxjs-es/add/operator/buffer.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/buffer'>;
}
declare module 'rxjs-es/add/operator/bufferCount.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/bufferCount'>;
}
declare module 'rxjs-es/add/operator/bufferTime.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/bufferTime'>;
}
declare module 'rxjs-es/add/operator/bufferToggle.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/bufferToggle'>;
}
declare module 'rxjs-es/add/operator/bufferWhen.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/bufferWhen'>;
}
declare module 'rxjs-es/add/operator/cache.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/cache'>;
}
declare module 'rxjs-es/add/operator/catch.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/catch'>;
}
declare module 'rxjs-es/add/operator/combineAll.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/combineAll'>;
}
declare module 'rxjs-es/add/operator/combineLatest.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/combineLatest'>;
}
declare module 'rxjs-es/add/operator/concat.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/concat'>;
}
declare module 'rxjs-es/add/operator/concatAll.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/concatAll'>;
}
declare module 'rxjs-es/add/operator/concatMap.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/concatMap'>;
}
declare module 'rxjs-es/add/operator/concatMapTo.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/concatMapTo'>;
}
declare module 'rxjs-es/add/operator/count.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/count'>;
}
declare module 'rxjs-es/add/operator/debounce.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/debounce'>;
}
declare module 'rxjs-es/add/operator/debounceTime.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/debounceTime'>;
}
declare module 'rxjs-es/add/operator/defaultIfEmpty.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/defaultIfEmpty'>;
}
declare module 'rxjs-es/add/operator/delay.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/delay'>;
}
declare module 'rxjs-es/add/operator/delayWhen.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/delayWhen'>;
}
declare module 'rxjs-es/add/operator/dematerialize.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/dematerialize'>;
}
declare module 'rxjs-es/add/operator/distinct.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/distinct'>;
}
declare module 'rxjs-es/add/operator/distinctKey.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/distinctKey'>;
}
declare module 'rxjs-es/add/operator/distinctUntilChanged.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/distinctUntilChanged'>;
}
declare module 'rxjs-es/add/operator/distinctUntilKeyChanged.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/distinctUntilKeyChanged'>;
}
declare module 'rxjs-es/add/operator/do.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/do'>;
}
declare module 'rxjs-es/add/operator/elementAt.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/elementAt'>;
}
declare module 'rxjs-es/add/operator/every.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/every'>;
}
declare module 'rxjs-es/add/operator/exhaust.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/exhaust'>;
}
declare module 'rxjs-es/add/operator/exhaustMap.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/exhaustMap'>;
}
declare module 'rxjs-es/add/operator/expand.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/expand'>;
}
declare module 'rxjs-es/add/operator/filter.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/filter'>;
}
declare module 'rxjs-es/add/operator/finally.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/finally'>;
}
declare module 'rxjs-es/add/operator/find.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/find'>;
}
declare module 'rxjs-es/add/operator/findIndex.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/findIndex'>;
}
declare module 'rxjs-es/add/operator/first.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/first'>;
}
declare module 'rxjs-es/add/operator/groupBy.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/groupBy'>;
}
declare module 'rxjs-es/add/operator/ignoreElements.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/ignoreElements'>;
}
declare module 'rxjs-es/add/operator/isEmpty.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/isEmpty'>;
}
declare module 'rxjs-es/add/operator/last.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/last'>;
}
declare module 'rxjs-es/add/operator/let.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/let'>;
}
declare module 'rxjs-es/add/operator/map.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/map'>;
}
declare module 'rxjs-es/add/operator/mapTo.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/mapTo'>;
}
declare module 'rxjs-es/add/operator/materialize.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/materialize'>;
}
declare module 'rxjs-es/add/operator/max.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/max'>;
}
declare module 'rxjs-es/add/operator/merge.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/merge'>;
}
declare module 'rxjs-es/add/operator/mergeAll.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/mergeAll'>;
}
declare module 'rxjs-es/add/operator/mergeMap.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/mergeMap'>;
}
declare module 'rxjs-es/add/operator/mergeMapTo.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/mergeMapTo'>;
}
declare module 'rxjs-es/add/operator/mergeScan.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/mergeScan'>;
}
declare module 'rxjs-es/add/operator/min.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/min'>;
}
declare module 'rxjs-es/add/operator/multicast.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/multicast'>;
}
declare module 'rxjs-es/add/operator/observeOn.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/observeOn'>;
}
declare module 'rxjs-es/add/operator/onErrorResumeNext.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/onErrorResumeNext'>;
}
declare module 'rxjs-es/add/operator/pairwise.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/pairwise'>;
}
declare module 'rxjs-es/add/operator/partition.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/partition'>;
}
declare module 'rxjs-es/add/operator/pluck.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/pluck'>;
}
declare module 'rxjs-es/add/operator/publish.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/publish'>;
}
declare module 'rxjs-es/add/operator/publishBehavior.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/publishBehavior'>;
}
declare module 'rxjs-es/add/operator/publishLast.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/publishLast'>;
}
declare module 'rxjs-es/add/operator/publishReplay.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/publishReplay'>;
}
declare module 'rxjs-es/add/operator/race.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/race'>;
}
declare module 'rxjs-es/add/operator/reduce.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/reduce'>;
}
declare module 'rxjs-es/add/operator/repeat.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/repeat'>;
}
declare module 'rxjs-es/add/operator/repeatWhen.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/repeatWhen'>;
}
declare module 'rxjs-es/add/operator/retry.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/retry'>;
}
declare module 'rxjs-es/add/operator/retryWhen.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/retryWhen'>;
}
declare module 'rxjs-es/add/operator/sample.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/sample'>;
}
declare module 'rxjs-es/add/operator/sampleTime.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/sampleTime'>;
}
declare module 'rxjs-es/add/operator/scan.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/scan'>;
}
declare module 'rxjs-es/add/operator/sequenceEqual.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/sequenceEqual'>;
}
declare module 'rxjs-es/add/operator/share.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/share'>;
}
declare module 'rxjs-es/add/operator/single.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/single'>;
}
declare module 'rxjs-es/add/operator/skip.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/skip'>;
}
declare module 'rxjs-es/add/operator/skipUntil.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/skipUntil'>;
}
declare module 'rxjs-es/add/operator/skipWhile.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/skipWhile'>;
}
declare module 'rxjs-es/add/operator/startWith.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/startWith'>;
}
declare module 'rxjs-es/add/operator/subscribeOn.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/subscribeOn'>;
}
declare module 'rxjs-es/add/operator/switch.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/switch'>;
}
declare module 'rxjs-es/add/operator/switchMap.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/switchMap'>;
}
declare module 'rxjs-es/add/operator/switchMapTo.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/switchMapTo'>;
}
declare module 'rxjs-es/add/operator/take.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/take'>;
}
declare module 'rxjs-es/add/operator/takeLast.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/takeLast'>;
}
declare module 'rxjs-es/add/operator/takeUntil.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/takeUntil'>;
}
declare module 'rxjs-es/add/operator/takeWhile.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/takeWhile'>;
}
declare module 'rxjs-es/add/operator/throttle.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/throttle'>;
}
declare module 'rxjs-es/add/operator/throttleTime.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/throttleTime'>;
}
declare module 'rxjs-es/add/operator/timeInterval.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/timeInterval'>;
}
declare module 'rxjs-es/add/operator/timeout.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/timeout'>;
}
declare module 'rxjs-es/add/operator/timeoutWith.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/timeoutWith'>;
}
declare module 'rxjs-es/add/operator/timestamp.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/timestamp'>;
}
declare module 'rxjs-es/add/operator/toArray.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/toArray'>;
}
declare module 'rxjs-es/add/operator/toPromise.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/toPromise'>;
}
declare module 'rxjs-es/add/operator/window.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/window'>;
}
declare module 'rxjs-es/add/operator/windowCount.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/windowCount'>;
}
declare module 'rxjs-es/add/operator/windowTime.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/windowTime'>;
}
declare module 'rxjs-es/add/operator/windowToggle.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/windowToggle'>;
}
declare module 'rxjs-es/add/operator/windowWhen.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/windowWhen'>;
}
declare module 'rxjs-es/add/operator/withLatestFrom.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/withLatestFrom'>;
}
declare module 'rxjs-es/add/operator/zip.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/zip'>;
}
declare module 'rxjs-es/add/operator/zipAll.js' {
  declare module.exports: $Exports<'rxjs-es/add/operator/zipAll'>;
}
declare module 'rxjs-es/AsyncSubject.js' {
  declare module.exports: $Exports<'rxjs-es/AsyncSubject'>;
}
declare module 'rxjs-es/BehaviorSubject.js' {
  declare module.exports: $Exports<'rxjs-es/BehaviorSubject'>;
}
declare module 'rxjs-es/InnerSubscriber.js' {
  declare module.exports: $Exports<'rxjs-es/InnerSubscriber'>;
}
declare module 'rxjs-es/Notification.js' {
  declare module.exports: $Exports<'rxjs-es/Notification'>;
}
declare module 'rxjs-es/Observable.js' {
  declare module.exports: $Exports<'rxjs-es/Observable'>;
}
declare module 'rxjs-es/observable/ArrayLikeObservable.js' {
  declare module.exports: $Exports<'rxjs-es/observable/ArrayLikeObservable'>;
}
declare module 'rxjs-es/observable/ArrayObservable.js' {
  declare module.exports: $Exports<'rxjs-es/observable/ArrayObservable'>;
}
declare module 'rxjs-es/observable/bindCallback.js' {
  declare module.exports: $Exports<'rxjs-es/observable/bindCallback'>;
}
declare module 'rxjs-es/observable/bindNodeCallback.js' {
  declare module.exports: $Exports<'rxjs-es/observable/bindNodeCallback'>;
}
declare module 'rxjs-es/observable/BoundCallbackObservable.js' {
  declare module.exports: $Exports<'rxjs-es/observable/BoundCallbackObservable'>;
}
declare module 'rxjs-es/observable/BoundNodeCallbackObservable.js' {
  declare module.exports: $Exports<'rxjs-es/observable/BoundNodeCallbackObservable'>;
}
declare module 'rxjs-es/observable/combineLatest.js' {
  declare module.exports: $Exports<'rxjs-es/observable/combineLatest'>;
}
declare module 'rxjs-es/observable/concat.js' {
  declare module.exports: $Exports<'rxjs-es/observable/concat'>;
}
declare module 'rxjs-es/observable/ConnectableObservable.js' {
  declare module.exports: $Exports<'rxjs-es/observable/ConnectableObservable'>;
}
declare module 'rxjs-es/observable/defer.js' {
  declare module.exports: $Exports<'rxjs-es/observable/defer'>;
}
declare module 'rxjs-es/observable/DeferObservable.js' {
  declare module.exports: $Exports<'rxjs-es/observable/DeferObservable'>;
}
declare module 'rxjs-es/observable/dom/ajax.js' {
  declare module.exports: $Exports<'rxjs-es/observable/dom/ajax'>;
}
declare module 'rxjs-es/observable/dom/AjaxObservable.js' {
  declare module.exports: $Exports<'rxjs-es/observable/dom/AjaxObservable'>;
}
declare module 'rxjs-es/observable/dom/webSocket.js' {
  declare module.exports: $Exports<'rxjs-es/observable/dom/webSocket'>;
}
declare module 'rxjs-es/observable/dom/WebSocketSubject.js' {
  declare module.exports: $Exports<'rxjs-es/observable/dom/WebSocketSubject'>;
}
declare module 'rxjs-es/observable/empty.js' {
  declare module.exports: $Exports<'rxjs-es/observable/empty'>;
}
declare module 'rxjs-es/observable/EmptyObservable.js' {
  declare module.exports: $Exports<'rxjs-es/observable/EmptyObservable'>;
}
declare module 'rxjs-es/observable/ErrorObservable.js' {
  declare module.exports: $Exports<'rxjs-es/observable/ErrorObservable'>;
}
declare module 'rxjs-es/observable/forkJoin.js' {
  declare module.exports: $Exports<'rxjs-es/observable/forkJoin'>;
}
declare module 'rxjs-es/observable/ForkJoinObservable.js' {
  declare module.exports: $Exports<'rxjs-es/observable/ForkJoinObservable'>;
}
declare module 'rxjs-es/observable/from.js' {
  declare module.exports: $Exports<'rxjs-es/observable/from'>;
}
declare module 'rxjs-es/observable/fromEvent.js' {
  declare module.exports: $Exports<'rxjs-es/observable/fromEvent'>;
}
declare module 'rxjs-es/observable/FromEventObservable.js' {
  declare module.exports: $Exports<'rxjs-es/observable/FromEventObservable'>;
}
declare module 'rxjs-es/observable/fromEventPattern.js' {
  declare module.exports: $Exports<'rxjs-es/observable/fromEventPattern'>;
}
declare module 'rxjs-es/observable/FromEventPatternObservable.js' {
  declare module.exports: $Exports<'rxjs-es/observable/FromEventPatternObservable'>;
}
declare module 'rxjs-es/observable/FromObservable.js' {
  declare module.exports: $Exports<'rxjs-es/observable/FromObservable'>;
}
declare module 'rxjs-es/observable/fromPromise.js' {
  declare module.exports: $Exports<'rxjs-es/observable/fromPromise'>;
}
declare module 'rxjs-es/observable/GenerateObservable.js' {
  declare module.exports: $Exports<'rxjs-es/observable/GenerateObservable'>;
}
declare module 'rxjs-es/observable/if.js' {
  declare module.exports: $Exports<'rxjs-es/observable/if'>;
}
declare module 'rxjs-es/observable/IfObservable.js' {
  declare module.exports: $Exports<'rxjs-es/observable/IfObservable'>;
}
declare module 'rxjs-es/observable/interval.js' {
  declare module.exports: $Exports<'rxjs-es/observable/interval'>;
}
declare module 'rxjs-es/observable/IntervalObservable.js' {
  declare module.exports: $Exports<'rxjs-es/observable/IntervalObservable'>;
}
declare module 'rxjs-es/observable/IteratorObservable.js' {
  declare module.exports: $Exports<'rxjs-es/observable/IteratorObservable'>;
}
declare module 'rxjs-es/observable/merge.js' {
  declare module.exports: $Exports<'rxjs-es/observable/merge'>;
}
declare module 'rxjs-es/observable/MulticastObservable.js' {
  declare module.exports: $Exports<'rxjs-es/observable/MulticastObservable'>;
}
declare module 'rxjs-es/observable/never.js' {
  declare module.exports: $Exports<'rxjs-es/observable/never'>;
}
declare module 'rxjs-es/observable/NeverObservable.js' {
  declare module.exports: $Exports<'rxjs-es/observable/NeverObservable'>;
}
declare module 'rxjs-es/observable/of.js' {
  declare module.exports: $Exports<'rxjs-es/observable/of'>;
}
declare module 'rxjs-es/observable/pairs.js' {
  declare module.exports: $Exports<'rxjs-es/observable/pairs'>;
}
declare module 'rxjs-es/observable/PairsObservable.js' {
  declare module.exports: $Exports<'rxjs-es/observable/PairsObservable'>;
}
declare module 'rxjs-es/observable/PromiseObservable.js' {
  declare module.exports: $Exports<'rxjs-es/observable/PromiseObservable'>;
}
declare module 'rxjs-es/observable/range.js' {
  declare module.exports: $Exports<'rxjs-es/observable/range'>;
}
declare module 'rxjs-es/observable/RangeObservable.js' {
  declare module.exports: $Exports<'rxjs-es/observable/RangeObservable'>;
}
declare module 'rxjs-es/observable/ScalarObservable.js' {
  declare module.exports: $Exports<'rxjs-es/observable/ScalarObservable'>;
}
declare module 'rxjs-es/observable/SubscribeOnObservable.js' {
  declare module.exports: $Exports<'rxjs-es/observable/SubscribeOnObservable'>;
}
declare module 'rxjs-es/observable/throw.js' {
  declare module.exports: $Exports<'rxjs-es/observable/throw'>;
}
declare module 'rxjs-es/observable/timer.js' {
  declare module.exports: $Exports<'rxjs-es/observable/timer'>;
}
declare module 'rxjs-es/observable/TimerObservable.js' {
  declare module.exports: $Exports<'rxjs-es/observable/TimerObservable'>;
}
declare module 'rxjs-es/observable/using.js' {
  declare module.exports: $Exports<'rxjs-es/observable/using'>;
}
declare module 'rxjs-es/observable/UsingObservable.js' {
  declare module.exports: $Exports<'rxjs-es/observable/UsingObservable'>;
}
declare module 'rxjs-es/observable/zip.js' {
  declare module.exports: $Exports<'rxjs-es/observable/zip'>;
}
declare module 'rxjs-es/Observer.js' {
  declare module.exports: $Exports<'rxjs-es/Observer'>;
}
declare module 'rxjs-es/Operator.js' {
  declare module.exports: $Exports<'rxjs-es/Operator'>;
}
declare module 'rxjs-es/operator/audit.js' {
  declare module.exports: $Exports<'rxjs-es/operator/audit'>;
}
declare module 'rxjs-es/operator/auditTime.js' {
  declare module.exports: $Exports<'rxjs-es/operator/auditTime'>;
}
declare module 'rxjs-es/operator/buffer.js' {
  declare module.exports: $Exports<'rxjs-es/operator/buffer'>;
}
declare module 'rxjs-es/operator/bufferCount.js' {
  declare module.exports: $Exports<'rxjs-es/operator/bufferCount'>;
}
declare module 'rxjs-es/operator/bufferTime.js' {
  declare module.exports: $Exports<'rxjs-es/operator/bufferTime'>;
}
declare module 'rxjs-es/operator/bufferToggle.js' {
  declare module.exports: $Exports<'rxjs-es/operator/bufferToggle'>;
}
declare module 'rxjs-es/operator/bufferWhen.js' {
  declare module.exports: $Exports<'rxjs-es/operator/bufferWhen'>;
}
declare module 'rxjs-es/operator/cache.js' {
  declare module.exports: $Exports<'rxjs-es/operator/cache'>;
}
declare module 'rxjs-es/operator/catch.js' {
  declare module.exports: $Exports<'rxjs-es/operator/catch'>;
}
declare module 'rxjs-es/operator/combineAll.js' {
  declare module.exports: $Exports<'rxjs-es/operator/combineAll'>;
}
declare module 'rxjs-es/operator/combineLatest.js' {
  declare module.exports: $Exports<'rxjs-es/operator/combineLatest'>;
}
declare module 'rxjs-es/operator/concat.js' {
  declare module.exports: $Exports<'rxjs-es/operator/concat'>;
}
declare module 'rxjs-es/operator/concatAll.js' {
  declare module.exports: $Exports<'rxjs-es/operator/concatAll'>;
}
declare module 'rxjs-es/operator/concatMap.js' {
  declare module.exports: $Exports<'rxjs-es/operator/concatMap'>;
}
declare module 'rxjs-es/operator/concatMapTo.js' {
  declare module.exports: $Exports<'rxjs-es/operator/concatMapTo'>;
}
declare module 'rxjs-es/operator/count.js' {
  declare module.exports: $Exports<'rxjs-es/operator/count'>;
}
declare module 'rxjs-es/operator/debounce.js' {
  declare module.exports: $Exports<'rxjs-es/operator/debounce'>;
}
declare module 'rxjs-es/operator/debounceTime.js' {
  declare module.exports: $Exports<'rxjs-es/operator/debounceTime'>;
}
declare module 'rxjs-es/operator/defaultIfEmpty.js' {
  declare module.exports: $Exports<'rxjs-es/operator/defaultIfEmpty'>;
}
declare module 'rxjs-es/operator/delay.js' {
  declare module.exports: $Exports<'rxjs-es/operator/delay'>;
}
declare module 'rxjs-es/operator/delayWhen.js' {
  declare module.exports: $Exports<'rxjs-es/operator/delayWhen'>;
}
declare module 'rxjs-es/operator/dematerialize.js' {
  declare module.exports: $Exports<'rxjs-es/operator/dematerialize'>;
}
declare module 'rxjs-es/operator/distinct.js' {
  declare module.exports: $Exports<'rxjs-es/operator/distinct'>;
}
declare module 'rxjs-es/operator/distinctKey.js' {
  declare module.exports: $Exports<'rxjs-es/operator/distinctKey'>;
}
declare module 'rxjs-es/operator/distinctUntilChanged.js' {
  declare module.exports: $Exports<'rxjs-es/operator/distinctUntilChanged'>;
}
declare module 'rxjs-es/operator/distinctUntilKeyChanged.js' {
  declare module.exports: $Exports<'rxjs-es/operator/distinctUntilKeyChanged'>;
}
declare module 'rxjs-es/operator/do.js' {
  declare module.exports: $Exports<'rxjs-es/operator/do'>;
}
declare module 'rxjs-es/operator/elementAt.js' {
  declare module.exports: $Exports<'rxjs-es/operator/elementAt'>;
}
declare module 'rxjs-es/operator/every.js' {
  declare module.exports: $Exports<'rxjs-es/operator/every'>;
}
declare module 'rxjs-es/operator/exhaust.js' {
  declare module.exports: $Exports<'rxjs-es/operator/exhaust'>;
}
declare module 'rxjs-es/operator/exhaustMap.js' {
  declare module.exports: $Exports<'rxjs-es/operator/exhaustMap'>;
}
declare module 'rxjs-es/operator/expand.js' {
  declare module.exports: $Exports<'rxjs-es/operator/expand'>;
}
declare module 'rxjs-es/operator/filter.js' {
  declare module.exports: $Exports<'rxjs-es/operator/filter'>;
}
declare module 'rxjs-es/operator/finally.js' {
  declare module.exports: $Exports<'rxjs-es/operator/finally'>;
}
declare module 'rxjs-es/operator/find.js' {
  declare module.exports: $Exports<'rxjs-es/operator/find'>;
}
declare module 'rxjs-es/operator/findIndex.js' {
  declare module.exports: $Exports<'rxjs-es/operator/findIndex'>;
}
declare module 'rxjs-es/operator/first.js' {
  declare module.exports: $Exports<'rxjs-es/operator/first'>;
}
declare module 'rxjs-es/operator/groupBy.js' {
  declare module.exports: $Exports<'rxjs-es/operator/groupBy'>;
}
declare module 'rxjs-es/operator/ignoreElements.js' {
  declare module.exports: $Exports<'rxjs-es/operator/ignoreElements'>;
}
declare module 'rxjs-es/operator/isEmpty.js' {
  declare module.exports: $Exports<'rxjs-es/operator/isEmpty'>;
}
declare module 'rxjs-es/operator/last.js' {
  declare module.exports: $Exports<'rxjs-es/operator/last'>;
}
declare module 'rxjs-es/operator/let.js' {
  declare module.exports: $Exports<'rxjs-es/operator/let'>;
}
declare module 'rxjs-es/operator/map.js' {
  declare module.exports: $Exports<'rxjs-es/operator/map'>;
}
declare module 'rxjs-es/operator/mapTo.js' {
  declare module.exports: $Exports<'rxjs-es/operator/mapTo'>;
}
declare module 'rxjs-es/operator/materialize.js' {
  declare module.exports: $Exports<'rxjs-es/operator/materialize'>;
}
declare module 'rxjs-es/operator/max.js' {
  declare module.exports: $Exports<'rxjs-es/operator/max'>;
}
declare module 'rxjs-es/operator/merge.js' {
  declare module.exports: $Exports<'rxjs-es/operator/merge'>;
}
declare module 'rxjs-es/operator/mergeAll.js' {
  declare module.exports: $Exports<'rxjs-es/operator/mergeAll'>;
}
declare module 'rxjs-es/operator/mergeMap.js' {
  declare module.exports: $Exports<'rxjs-es/operator/mergeMap'>;
}
declare module 'rxjs-es/operator/mergeMapTo.js' {
  declare module.exports: $Exports<'rxjs-es/operator/mergeMapTo'>;
}
declare module 'rxjs-es/operator/mergeScan.js' {
  declare module.exports: $Exports<'rxjs-es/operator/mergeScan'>;
}
declare module 'rxjs-es/operator/min.js' {
  declare module.exports: $Exports<'rxjs-es/operator/min'>;
}
declare module 'rxjs-es/operator/multicast.js' {
  declare module.exports: $Exports<'rxjs-es/operator/multicast'>;
}
declare module 'rxjs-es/operator/observeOn.js' {
  declare module.exports: $Exports<'rxjs-es/operator/observeOn'>;
}
declare module 'rxjs-es/operator/onErrorResumeNext.js' {
  declare module.exports: $Exports<'rxjs-es/operator/onErrorResumeNext'>;
}
declare module 'rxjs-es/operator/pairwise.js' {
  declare module.exports: $Exports<'rxjs-es/operator/pairwise'>;
}
declare module 'rxjs-es/operator/partition.js' {
  declare module.exports: $Exports<'rxjs-es/operator/partition'>;
}
declare module 'rxjs-es/operator/pluck.js' {
  declare module.exports: $Exports<'rxjs-es/operator/pluck'>;
}
declare module 'rxjs-es/operator/publish.js' {
  declare module.exports: $Exports<'rxjs-es/operator/publish'>;
}
declare module 'rxjs-es/operator/publishBehavior.js' {
  declare module.exports: $Exports<'rxjs-es/operator/publishBehavior'>;
}
declare module 'rxjs-es/operator/publishLast.js' {
  declare module.exports: $Exports<'rxjs-es/operator/publishLast'>;
}
declare module 'rxjs-es/operator/publishReplay.js' {
  declare module.exports: $Exports<'rxjs-es/operator/publishReplay'>;
}
declare module 'rxjs-es/operator/race.js' {
  declare module.exports: $Exports<'rxjs-es/operator/race'>;
}
declare module 'rxjs-es/operator/reduce.js' {
  declare module.exports: $Exports<'rxjs-es/operator/reduce'>;
}
declare module 'rxjs-es/operator/repeat.js' {
  declare module.exports: $Exports<'rxjs-es/operator/repeat'>;
}
declare module 'rxjs-es/operator/repeatWhen.js' {
  declare module.exports: $Exports<'rxjs-es/operator/repeatWhen'>;
}
declare module 'rxjs-es/operator/retry.js' {
  declare module.exports: $Exports<'rxjs-es/operator/retry'>;
}
declare module 'rxjs-es/operator/retryWhen.js' {
  declare module.exports: $Exports<'rxjs-es/operator/retryWhen'>;
}
declare module 'rxjs-es/operator/sample.js' {
  declare module.exports: $Exports<'rxjs-es/operator/sample'>;
}
declare module 'rxjs-es/operator/sampleTime.js' {
  declare module.exports: $Exports<'rxjs-es/operator/sampleTime'>;
}
declare module 'rxjs-es/operator/scan.js' {
  declare module.exports: $Exports<'rxjs-es/operator/scan'>;
}
declare module 'rxjs-es/operator/sequenceEqual.js' {
  declare module.exports: $Exports<'rxjs-es/operator/sequenceEqual'>;
}
declare module 'rxjs-es/operator/share.js' {
  declare module.exports: $Exports<'rxjs-es/operator/share'>;
}
declare module 'rxjs-es/operator/single.js' {
  declare module.exports: $Exports<'rxjs-es/operator/single'>;
}
declare module 'rxjs-es/operator/skip.js' {
  declare module.exports: $Exports<'rxjs-es/operator/skip'>;
}
declare module 'rxjs-es/operator/skipUntil.js' {
  declare module.exports: $Exports<'rxjs-es/operator/skipUntil'>;
}
declare module 'rxjs-es/operator/skipWhile.js' {
  declare module.exports: $Exports<'rxjs-es/operator/skipWhile'>;
}
declare module 'rxjs-es/operator/startWith.js' {
  declare module.exports: $Exports<'rxjs-es/operator/startWith'>;
}
declare module 'rxjs-es/operator/subscribeOn.js' {
  declare module.exports: $Exports<'rxjs-es/operator/subscribeOn'>;
}
declare module 'rxjs-es/operator/switch.js' {
  declare module.exports: $Exports<'rxjs-es/operator/switch'>;
}
declare module 'rxjs-es/operator/switchMap.js' {
  declare module.exports: $Exports<'rxjs-es/operator/switchMap'>;
}
declare module 'rxjs-es/operator/switchMapTo.js' {
  declare module.exports: $Exports<'rxjs-es/operator/switchMapTo'>;
}
declare module 'rxjs-es/operator/take.js' {
  declare module.exports: $Exports<'rxjs-es/operator/take'>;
}
declare module 'rxjs-es/operator/takeLast.js' {
  declare module.exports: $Exports<'rxjs-es/operator/takeLast'>;
}
declare module 'rxjs-es/operator/takeUntil.js' {
  declare module.exports: $Exports<'rxjs-es/operator/takeUntil'>;
}
declare module 'rxjs-es/operator/takeWhile.js' {
  declare module.exports: $Exports<'rxjs-es/operator/takeWhile'>;
}
declare module 'rxjs-es/operator/throttle.js' {
  declare module.exports: $Exports<'rxjs-es/operator/throttle'>;
}
declare module 'rxjs-es/operator/throttleTime.js' {
  declare module.exports: $Exports<'rxjs-es/operator/throttleTime'>;
}
declare module 'rxjs-es/operator/timeInterval.js' {
  declare module.exports: $Exports<'rxjs-es/operator/timeInterval'>;
}
declare module 'rxjs-es/operator/timeout.js' {
  declare module.exports: $Exports<'rxjs-es/operator/timeout'>;
}
declare module 'rxjs-es/operator/timeoutWith.js' {
  declare module.exports: $Exports<'rxjs-es/operator/timeoutWith'>;
}
declare module 'rxjs-es/operator/timestamp.js' {
  declare module.exports: $Exports<'rxjs-es/operator/timestamp'>;
}
declare module 'rxjs-es/operator/toArray.js' {
  declare module.exports: $Exports<'rxjs-es/operator/toArray'>;
}
declare module 'rxjs-es/operator/toPromise.js' {
  declare module.exports: $Exports<'rxjs-es/operator/toPromise'>;
}
declare module 'rxjs-es/operator/window.js' {
  declare module.exports: $Exports<'rxjs-es/operator/window'>;
}
declare module 'rxjs-es/operator/windowCount.js' {
  declare module.exports: $Exports<'rxjs-es/operator/windowCount'>;
}
declare module 'rxjs-es/operator/windowTime.js' {
  declare module.exports: $Exports<'rxjs-es/operator/windowTime'>;
}
declare module 'rxjs-es/operator/windowToggle.js' {
  declare module.exports: $Exports<'rxjs-es/operator/windowToggle'>;
}
declare module 'rxjs-es/operator/windowWhen.js' {
  declare module.exports: $Exports<'rxjs-es/operator/windowWhen'>;
}
declare module 'rxjs-es/operator/withLatestFrom.js' {
  declare module.exports: $Exports<'rxjs-es/operator/withLatestFrom'>;
}
declare module 'rxjs-es/operator/zip.js' {
  declare module.exports: $Exports<'rxjs-es/operator/zip'>;
}
declare module 'rxjs-es/operator/zipAll.js' {
  declare module.exports: $Exports<'rxjs-es/operator/zipAll'>;
}
declare module 'rxjs-es/OuterSubscriber.js' {
  declare module.exports: $Exports<'rxjs-es/OuterSubscriber'>;
}
declare module 'rxjs-es/ReplaySubject.js' {
  declare module.exports: $Exports<'rxjs-es/ReplaySubject'>;
}
declare module 'rxjs-es/Rx.js' {
  declare module.exports: $Exports<'rxjs-es/Rx'>;
}
declare module 'rxjs-es/Scheduler.js' {
  declare module.exports: $Exports<'rxjs-es/Scheduler'>;
}
declare module 'rxjs-es/scheduler/Action.js' {
  declare module.exports: $Exports<'rxjs-es/scheduler/Action'>;
}
declare module 'rxjs-es/scheduler/animationFrame.js' {
  declare module.exports: $Exports<'rxjs-es/scheduler/animationFrame'>;
}
declare module 'rxjs-es/scheduler/AnimationFrameAction.js' {
  declare module.exports: $Exports<'rxjs-es/scheduler/AnimationFrameAction'>;
}
declare module 'rxjs-es/scheduler/AnimationFrameScheduler.js' {
  declare module.exports: $Exports<'rxjs-es/scheduler/AnimationFrameScheduler'>;
}
declare module 'rxjs-es/scheduler/asap.js' {
  declare module.exports: $Exports<'rxjs-es/scheduler/asap'>;
}
declare module 'rxjs-es/scheduler/AsapAction.js' {
  declare module.exports: $Exports<'rxjs-es/scheduler/AsapAction'>;
}
declare module 'rxjs-es/scheduler/AsapScheduler.js' {
  declare module.exports: $Exports<'rxjs-es/scheduler/AsapScheduler'>;
}
declare module 'rxjs-es/scheduler/async.js' {
  declare module.exports: $Exports<'rxjs-es/scheduler/async'>;
}
declare module 'rxjs-es/scheduler/AsyncAction.js' {
  declare module.exports: $Exports<'rxjs-es/scheduler/AsyncAction'>;
}
declare module 'rxjs-es/scheduler/AsyncScheduler.js' {
  declare module.exports: $Exports<'rxjs-es/scheduler/AsyncScheduler'>;
}
declare module 'rxjs-es/scheduler/queue.js' {
  declare module.exports: $Exports<'rxjs-es/scheduler/queue'>;
}
declare module 'rxjs-es/scheduler/QueueAction.js' {
  declare module.exports: $Exports<'rxjs-es/scheduler/QueueAction'>;
}
declare module 'rxjs-es/scheduler/QueueScheduler.js' {
  declare module.exports: $Exports<'rxjs-es/scheduler/QueueScheduler'>;
}
declare module 'rxjs-es/scheduler/VirtualTimeScheduler.js' {
  declare module.exports: $Exports<'rxjs-es/scheduler/VirtualTimeScheduler'>;
}
declare module 'rxjs-es/src/Rx.global.js' {
  declare module.exports: $Exports<'rxjs-es/src/Rx.global'>;
}
declare module 'rxjs-es/Subject.js' {
  declare module.exports: $Exports<'rxjs-es/Subject'>;
}
declare module 'rxjs-es/SubjectSubscription.js' {
  declare module.exports: $Exports<'rxjs-es/SubjectSubscription'>;
}
declare module 'rxjs-es/Subscriber.js' {
  declare module.exports: $Exports<'rxjs-es/Subscriber'>;
}
declare module 'rxjs-es/Subscription.js' {
  declare module.exports: $Exports<'rxjs-es/Subscription'>;
}
declare module 'rxjs-es/symbol/iterator.js' {
  declare module.exports: $Exports<'rxjs-es/symbol/iterator'>;
}
declare module 'rxjs-es/symbol/observable.js' {
  declare module.exports: $Exports<'rxjs-es/symbol/observable'>;
}
declare module 'rxjs-es/symbol/rxSubscriber.js' {
  declare module.exports: $Exports<'rxjs-es/symbol/rxSubscriber'>;
}
declare module 'rxjs-es/testing/ColdObservable.js' {
  declare module.exports: $Exports<'rxjs-es/testing/ColdObservable'>;
}
declare module 'rxjs-es/testing/HotObservable.js' {
  declare module.exports: $Exports<'rxjs-es/testing/HotObservable'>;
}
declare module 'rxjs-es/testing/SubscriptionLog.js' {
  declare module.exports: $Exports<'rxjs-es/testing/SubscriptionLog'>;
}
declare module 'rxjs-es/testing/SubscriptionLoggable.js' {
  declare module.exports: $Exports<'rxjs-es/testing/SubscriptionLoggable'>;
}
declare module 'rxjs-es/testing/TestMessage.js' {
  declare module.exports: $Exports<'rxjs-es/testing/TestMessage'>;
}
declare module 'rxjs-es/testing/TestScheduler.js' {
  declare module.exports: $Exports<'rxjs-es/testing/TestScheduler'>;
}
declare module 'rxjs-es/util/AnimationFrame.js' {
  declare module.exports: $Exports<'rxjs-es/util/AnimationFrame'>;
}
declare module 'rxjs-es/util/applyMixins.js' {
  declare module.exports: $Exports<'rxjs-es/util/applyMixins'>;
}
declare module 'rxjs-es/util/ArgumentOutOfRangeError.js' {
  declare module.exports: $Exports<'rxjs-es/util/ArgumentOutOfRangeError'>;
}
declare module 'rxjs-es/util/assign.js' {
  declare module.exports: $Exports<'rxjs-es/util/assign'>;
}
declare module 'rxjs-es/util/EmptyError.js' {
  declare module.exports: $Exports<'rxjs-es/util/EmptyError'>;
}
declare module 'rxjs-es/util/errorObject.js' {
  declare module.exports: $Exports<'rxjs-es/util/errorObject'>;
}
declare module 'rxjs-es/util/FastMap.js' {
  declare module.exports: $Exports<'rxjs-es/util/FastMap'>;
}
declare module 'rxjs-es/util/Immediate.js' {
  declare module.exports: $Exports<'rxjs-es/util/Immediate'>;
}
declare module 'rxjs-es/util/isArray.js' {
  declare module.exports: $Exports<'rxjs-es/util/isArray'>;
}
declare module 'rxjs-es/util/isDate.js' {
  declare module.exports: $Exports<'rxjs-es/util/isDate'>;
}
declare module 'rxjs-es/util/isFunction.js' {
  declare module.exports: $Exports<'rxjs-es/util/isFunction'>;
}
declare module 'rxjs-es/util/isNumeric.js' {
  declare module.exports: $Exports<'rxjs-es/util/isNumeric'>;
}
declare module 'rxjs-es/util/isObject.js' {
  declare module.exports: $Exports<'rxjs-es/util/isObject'>;
}
declare module 'rxjs-es/util/isPromise.js' {
  declare module.exports: $Exports<'rxjs-es/util/isPromise'>;
}
declare module 'rxjs-es/util/isScheduler.js' {
  declare module.exports: $Exports<'rxjs-es/util/isScheduler'>;
}
declare module 'rxjs-es/util/Map.js' {
  declare module.exports: $Exports<'rxjs-es/util/Map'>;
}
declare module 'rxjs-es/util/MapPolyfill.js' {
  declare module.exports: $Exports<'rxjs-es/util/MapPolyfill'>;
}
declare module 'rxjs-es/util/noop.js' {
  declare module.exports: $Exports<'rxjs-es/util/noop'>;
}
declare module 'rxjs-es/util/not.js' {
  declare module.exports: $Exports<'rxjs-es/util/not'>;
}
declare module 'rxjs-es/util/ObjectUnsubscribedError.js' {
  declare module.exports: $Exports<'rxjs-es/util/ObjectUnsubscribedError'>;
}
declare module 'rxjs-es/util/root.js' {
  declare module.exports: $Exports<'rxjs-es/util/root'>;
}
declare module 'rxjs-es/util/subscribeToResult.js' {
  declare module.exports: $Exports<'rxjs-es/util/subscribeToResult'>;
}
declare module 'rxjs-es/util/toSubscriber.js' {
  declare module.exports: $Exports<'rxjs-es/util/toSubscriber'>;
}
declare module 'rxjs-es/util/tryCatch.js' {
  declare module.exports: $Exports<'rxjs-es/util/tryCatch'>;
}
declare module 'rxjs-es/util/UnsubscriptionError.js' {
  declare module.exports: $Exports<'rxjs-es/util/UnsubscriptionError'>;
}
